#!/bin/bash
# Local variables in simple command
# REQUIRES: LOCAL

FILES=
PROGS="echo printenv"
/c/cs323/bin/Exist $FILES && exit

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bash $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 1000

################

$RUN ./Bash <<\END
  A=aardvark B=bluebird C=cardinal /usr/bin/printenv A B C
  echo End of test
END

echo
