#!/bin/bash
# Redirect stdout to nonexistent/writable file
# REQUIRES: REDIR (>)

FILES="+Bash.tmp"
PROGS="cat echo"
/c/cs323/bin/Exist $FILES && exit

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bash $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 1000

################

$RUN ./Bash <<\END
  # Nonexistent file
  cat /c/cs323/proj4/tests/star.wars > +Bash.tmp
  cat +Bash.tmp
   
  # Writable file
  cat /c/cs323/proj4/tests/stk.txt   > +Bash.tmp
  cat +Bash.tmp
   
  echo End of test
END

echo
