#!/bin/bash
# Very long pipeline using few descriptors
# REQUIRES: PIPE

FILES=
PROGS="die cat echo fmt"
/c/cs323/bin/Exist $FILES && exit

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bash $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 1000

################

$RUN -desc=9 ./Bash <<\END
  # Verify correctness
  /c/cs323/proj4/tests/die 1 cat /c/cs323/proj4/tests/stk.txt | /usr/bin/fmt -48

  # Very long pipeline
  cat /c/cs323/Doc/Valgrind | cat -e | cat -e | cat -e | cat -e | cat -e
  echo End of test
END

echo
