#!/bin/bash
# Simple background command
# REQUIRES: BG & COMPLETE

ERROR="+Bash.err.$$"

FILES="$ERROR"
PROGS="echo sleep sleeper"
/c/cs323/bin/Exist $FILES && exit

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bash $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 1000

################

$RUN ./Bash <<\END 2>$ERROR
  echo As simple as
  /c/cs323/proj4/tests/sleeper alpha 0.4 gamma & sleep 0.2
  echo beta
  /usr/bin/sleep 0.4
  echo End of test
END

echo

/c/cs323/proj4/tests/suppress $ERROR
