#!/bin/bash

# \undef: Simple case

/usr/bin/valgrind -q ./proj1 <<END
\def{A}{aardvark}
\ifdef{A}{Output this text.}{Do not output this text.}
\undef{A}
\ifdef{A}{Do not output this text.}{Output this text.}
END
