#!/bin/bash

# Escaped characters: Simple

TESTS=/c/cs323/proj1/tests

/usr/bin/valgrind -q ./proj1 < $TESTS/t14x

echo -----

/usr/bin/valgrind -q ./proj1   $TESTS/t14x

echo -----

/usr/bin/valgrind -q ./proj1 <<'END'
\def{escape}{To escape a # precede it by a backslash}
\escape{\\}
\escape{\{}
\escape{\}}
END
