#!/bin/bash

# Linear time/space: Very long input with no macros

TESTS=/c/cs323/proj1/tests
RUN=/c/cs323/bin/run

$TESTS/t16.pl   100000 | /usr/bin/valgrind -q            ./proj1 | /usr/bin/wc -c
		
export MALLOC_MMAP_THRESHOLD_=$((16*1024*1024))

$TESTS/t16.pl  1000000 | LD_PRELOAD=$TESTS/librealloc.so ./proj1 | /usr/bin/wc -c

$TESTS/t16.pl 10000000 | LD_PRELOAD=$TESTS/librealloc.so ./proj1 | /usr/bin/wc -c


# Repeat Test #15 to penalize declaration of large buffers
$TESTS/t15
